[project]
name = "cortex-xsoar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible>=12.2.0",
    "ansible-core>=2.19.4",
    "pip>=25.3",
]
